image: generic-package-build-debian:v1

stages:
  - build
  - test
  - deploy

build_debian:
  stage: build
  tags:
    - debian
  before_script:
    - apt update && apt -y install build-essential libboost-all-dev cmake libtclap-dev pkg-config libcairo2-dev libglm-dev
  script:
    - mkdir build
    - cd build
    - cmake ../src
    - make -j3
  artifacts:
    when: on_success
    paths:
      - edp
    expire_in: 2 hours