image: generic-package-build-debian:v1

stages:
  - build
  - test
  - deploy

build_debian:
  stage: build
  tags:
    - debian-build
  before_script:
    - apt update && apt -y install build-essential libboost-all-dev cmake libtclap-dev pkg-config libcairo2-dev libglm-dev
  script:
    - mkdir build
    - cd build
    - cmake ../src
    - make -j3
  artifacts:
    when: on_success
    paths:
      - build/edp
    expire_in: 2 hours

deploy_debian:
  stage: deploy
  tags:
    - debian-build
  before_script:
    - apt update && apt -y install build-essential libboost-all-dev cmake libtclap-dev pkg-config libcairo2-dev libglm-dev binutils
  script:
    - bash build_deb.sh
  artifacts:
    when: on_success
    paths:
      - "edp*.deb"
    expire_in: 2 hours

repository:
    stage: deploy
    variables:
      DEPLOYKEY: "$DeployKey"
    tags:
      - debian-build
    script:
      - echo "-----BEGIN RSA PRIVATE KEY-----\n{DEPLOYKEY}\n-----END RSA PRIVATE KEY-----" > key
      - scp edp*.deb ivo@st-a1960.chem.tue.nl:/home/ivo/mydebs
