name: C/C++ CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y libeigen3-dev libboost-all-dev libtclap-dev libcppunit-dev libcairo2-dev
    - name: Configure CMake
      run: mkdir build && cd build && cmake ../src
    - name: Build
      run: cd build && make
    - name: Perform unit tests
      run: cd build && make test
